/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/users/disciplines/join/{disciplineCode}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Join discipline by code */
    post: operations['joinDiscipline'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/disciplines': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Find all disciplines */
    get: operations['getAll'];
    put?: never;
    /** Create a new discipline */
    post: operations['create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/activities/{disciplineId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a new activity */
    post: operations['create_1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Find my user */
    get: operations['getAuthenticatedUser'];
    put?: never;
    post?: never;
    /** Delete a user */
    delete: operations['delete'];
    options?: never;
    head?: never;
    /** Update user data */
    patch: operations['update'];
    trace?: never;
  };
  '/users/disciplines/{disciplineId}/revoke/target/{targetUserId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Revoke user moderator status */
    patch: operations['revokeModerator'];
    trace?: never;
  };
  '/users/disciplines/{disciplineId}/promote/target/{targetUserId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Promote user to moderator */
    patch: operations['promoteToModerator'];
    trace?: never;
  };
  '/users/activities/my/activities/{activityId}/status/{status}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update a activity status */
    patch: operations['updateActivityStatus'];
    trace?: never;
  };
  '/disciplines/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Find discipline by ID */
    get: operations['getById'];
    put?: never;
    post?: never;
    /** Delete a discipline */
    delete: operations['delete_1'];
    options?: never;
    head?: never;
    /** Update discipline data */
    patch: operations['update_1'];
    trace?: never;
  };
  '/activities/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Find activity by ID */
    get: operations['findById'];
    put?: never;
    post?: never;
    /** Delete a activity */
    delete: operations['delete_2'];
    options?: never;
    head?: never;
    /** Update activity data */
    patch: operations['update_2'];
    trace?: never;
  };
  '/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Find user by ID */
    get: operations['findById_1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/disciplines/my/disciplines': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List user disciplines */
    get: operations['listUserDisciplines'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/disciplines/disciplines/{disciplineId}/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List discipline members */
    get: operations['listDisciplineMembers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/activities/my/activities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all user activities */
    get: operations['listUserActivities'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/activities/my/activities/pending': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all pending user activities */
    get: operations['listPendingActivities'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/activities/my/activities/overdue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all overdue user activities */
    get: operations['listOverdueActivities'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/activities/my/activities/completed': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all completed user activities */
    get: operations['listCompletedActivities'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/disciplines/disciplines/{disciplineId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Leave discipline by id */
    delete: operations['leaveDiscipline'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    DisciplineRequestDTO: {
      name: string;
      description?: string;
      professor: string;
    };
    DisciplineResponseDTO: {
      /** Format: int64 */
      id?: number;
      name?: string;
      description?: string;
      professor?: string;
      disciplineCode?: string;
      hive?: components['schemas']['HiveResponseDTO'];
    };
    HiveResponseDTO: {
      /** Format: int32 */
      health?: number;
      /** Format: int32 */
      honeyLevel?: number;
    };
    RegisterUserRequestDTO: {
      name: string;
      email: string;
      password: string;
    };
    RegisterUserResponseDTO: {
      name?: string;
      email?: string;
    };
    LoginUserRequestDTO: {
      email: string;
      password: string;
    };
    LoginResponseDTO: {
      token?: string;
    };
    ActivityRequestDTO: {
      title: string;
      description?: string;
      /** @enum {string} */
      type: 'EXERCISE' | 'PROJECT' | 'EXAM';
      /** Format: date-time */
      deadline?: string;
    };
    ActivityResponseDTO: {
      /** Format: int64 */
      id?: number;
      title?: string;
      description?: string;
      /** @enum {string} */
      type?: 'EXERCISE' | 'PROJECT' | 'EXAM';
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      deadline?: string;
    };
    UserUpdateDTO: {
      name?: string;
      /** Format: email */
      email?: string;
    };
    UserResponseDTO: {
      /** Format: int64 */
      id?: number;
      name?: string;
      email?: string;
      /** Format: int32 */
      honey?: number;
    };
    UserActivityResponseDTO: {
      /** Format: int64 */
      userId?: number;
      /** Format: int64 */
      activityId?: number;
      /** @enum {string} */
      activityStatus?: 'COMPLETED' | 'PENDING';
      /** Format: date-time */
      completedAt?: string;
      /** Format: int32 */
      earnedHoney?: number;
    };
    DisciplineUpdateDTO: {
      name?: string;
      description?: string;
      professor?: string;
    };
    ActivityUpdateDTO: {
      title?: string;
      description?: string;
      /** @enum {string} */
      type?: 'EXERCISE' | 'PROJECT' | 'EXAM';
      /** Format: date-time */
      deadline?: string;
    };
    UserDisciplineResponseDTO: {
      /** Format: int64 */
      userId?: number;
      userName?: string;
      /** Format: int64 */
      disciplineId?: number;
      disciplineName?: string;
      isModerator?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  joinDiscipline: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        disciplineCode: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['DisciplineResponseDTO'][];
        };
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DisciplineRequestDTO'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['DisciplineResponseDTO'];
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterUserRequestDTO'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['RegisterUserResponseDTO'];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginUserRequestDTO'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['LoginResponseDTO'];
        };
      };
    };
  };
  create_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        disciplineId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivityRequestDTO'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ActivityResponseDTO'];
        };
      };
    };
  };
  getAuthenticatedUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['UserResponseDTO'];
        };
      };
    };
  };
  delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdateDTO'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['UserResponseDTO'];
        };
      };
    };
  };
  revokeModerator: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        targetUserId: number;
        disciplineId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  promoteToModerator: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        targetUserId: number;
        disciplineId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateActivityStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        activityId: number;
        status: 'COMPLETED' | 'PENDING';
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['UserActivityResponseDTO'];
        };
      };
    };
  };
  getById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['DisciplineResponseDTO'];
        };
      };
    };
  };
  delete_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DisciplineUpdateDTO'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['DisciplineResponseDTO'];
        };
      };
    };
  };
  findById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ActivityResponseDTO'];
        };
      };
    };
  };
  delete_2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivityUpdateDTO'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ActivityResponseDTO'];
        };
      };
    };
  };
  findById_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['UserResponseDTO'];
        };
      };
    };
  };
  listUserDisciplines: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['UserDisciplineResponseDTO'][];
        };
      };
    };
  };
  listDisciplineMembers: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        disciplineId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['UserDisciplineResponseDTO'][];
        };
      };
    };
  };
  listUserActivities: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['UserActivityResponseDTO'][];
        };
      };
    };
  };
  listPendingActivities: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['UserActivityResponseDTO'][];
        };
      };
    };
  };
  listOverdueActivities: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['UserActivityResponseDTO'][];
        };
      };
    };
  };
  listCompletedActivities: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['UserActivityResponseDTO'][];
        };
      };
    };
  };
  leaveDiscipline: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        disciplineId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
